version: '3.3'
services: 
  front:
    image: front:0.0.1-SNAPSHOT
    ports: 
      - 8080:8080
    depends_on: 
      - eureka
      - back
  eureka:
    image: eureka:0.0.1-SNAPSHOT
    ports: 
      - 8761:8761
  back:
    image: back:0.0.1-SNAPSHOT
    depends_on: 
      - mysql
      - eureka
    ports:
      - 8082:8080
  mysql:
    image: mysql:8.0.16
    environment: 
      - "MYSQL_ROOT_PASSWORD=ROOT"