version: '3.3'
services:
  front-server:
    build: ./ejemplo15mvcRestTemplateLoadBalancer
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - back-server
  eureka-server:
    build: ./ejemplo13cloudEureka
    ports:
      - 8761:8761 
  back-server:
    build: ./ejemplo10restJpa
    depends_on:
      - mysql-server
      - eureka-server
    ports:
      - 8082:8080
  back-server-2:
    build: ./ejemplo10restJpa
    depends_on:
      - mysql-server
      - eureka-server
  back-server-3:
    build: ./ejemplo10restJpa
    depends_on:
      - mysql-server
      - eureka-server
  mysql-server:
    image: mysql:8.0.16
    environment:
      - "MYSQL_ROOT_PASSWORD=root"